# Generated by Django 4.0.6 on 2022-08-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_addressmodelmixin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('park_name', models.CharField(max_length=250)),
                ('court_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('court_surface', models.CharField(choices=[('Hard Court', 'Hard Court'), ('Grass Court', 'Grass Court'), ('Clay Court', 'Clay Court')], default='Hard Court', max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
