# Generated by Django 4.0.6 on 2022-08-13 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_court'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodelmixin',
            name='address1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('addressmodelmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.addressmodelmixin')),
                ('user_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('api.addressmodelmixin',),
        ),
        migrations.CreateModel(
            name='CourtAddress',
            fields=[
                ('addressmodelmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.addressmodelmixin')),
                ('court_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='api.court')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.addressmodelmixin',),
        ),
    ]
