# Generated by Django 4.0.6 on 2022-08-13 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_addressmodelmixin_address1_useraddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('session_type', models.CharField(choices=[('Casual', 'Casual'), ('Competitive', 'Competitive')], max_length=250)),
                ('match_type', models.CharField(choices=[('Singles', 'Singles'), ('Competitive', 'Doubles')], default='Singles', max_length=250)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_session', to=settings.AUTH_USER_MODEL)),
                ('locatation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_session', to='api.court')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
