# Generated by Django 4.0.6 on 2022-08-13 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_court_address_courtaddress_court_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='locatation',
            new_name='location',
        ),
    ]
