# Generated by Django 4.0.6 on 2022-08-16 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_profile_ntrp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ntrp_rating',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
