# Generated by Django 4.0.6 on 2022-08-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_profile_ntrp_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ntrp',
            new_name='ntrp_rating',
        ),
    ]
