# Generated by Django 4.0.6 on 2022-08-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_ntrp_profile_ntrp_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
