# Generated by Django 4.0.6 on 2022-08-16 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtaddress',
            name='court',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='api.court'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL),
        ),
    ]
