# Generated by Django 4.0.6 on 2022-08-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_courtaddress_court_alter_useraddress_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='guest',
            constraint=models.UniqueConstraint(fields=('user', 'game_session'), name='unique_game_sessoin_follow'),
        ),
    ]
