# Generated by Django 4.0.6 on 2022-08-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_guest_game_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
