# Generated by Django 4.0.6 on 2022-08-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_gamesession_confirmed'),
        ('api', '0020_alter_notificationgamesession_game_session_and_more'),
    ]

    operations = [
    ]
