# Generated by Django 4.0.6 on 2022-08-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_merge_20220822_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image_file',
            field=models.ImageField(blank=True, max_length=600, null=True, upload_to='profile_images'),
        ),
    ]
