# Generated by Django 4.0.6 on 2022-08-23 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_profile_profile_image_file'),
        ('api', '0023_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
    ]
