# Generated by Django 4.0.6 on 2022-08-23 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_merge_20220823_2312'),
        ('api', '0025_alter_surveyresponse_about_court_and_more'),
    ]

    operations = [
    ]
