# Generated by Django 4.0.6 on 2022-08-24 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_merge_20220823_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='about_court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_court', to='api.court'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='about_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
