# Generated by Django 4.0.6 on 2022-08-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_survey_game_session_alter_survey_respondent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Wait Listed', 'Wait Listed'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Host', 'Host')], default='Pending', max_length=250),
        ),
    ]
