# Generated by Django 4.0.6 on 2022-08-27 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_guest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='date',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='time',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesession',
            name='endtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
