# Generated by Django 4.0.6 on 2022-08-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_gamesession_date_remove_gamesession_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
