# Generated by Django 4.0.6 on 2022-08-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_gamesession_endtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='full',
            field=models.BooleanField(default=False),
        ),
    ]
