# Generated by Django 4.0.6 on 2022-08-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_gamesession_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wins',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
