# Generated by Django 4.0.6 on 2022-08-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_rename_wins_profile_wins_losses'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='teammate_ntrp',
            field=models.CharField(choices=[('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7')], default='2.5', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='teammate_rank',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze')], default='Bronze', max_length=10),
        ),
    ]
