# Generated by Django 4.0.6 on 2022-08-30 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_rankupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankupdate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankupdate', to=settings.AUTH_USER_MODEL),
        ),
    ]
