# Generated by Django 4.0.6 on 2022-08-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_rankupdate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='teammate_rank',
            field=models.CharField(choices=[('#daa520', '#daa520'), ('#a9a9a9', '#a9a9a9'), ('#904d00', '#904d00')], default='#904d00', max_length=10),
        ),
        migrations.AlterField(
            model_name='rankupdate',
            name='tm_rank',
            field=models.CharField(choices=[('#daa520', '#daa520'), ('#a9a9a9', '#a9a9a9'), ('#904d00', '#904d00')], default='#904d00', max_length=10),
        ),
    ]
